# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
name:        sublinear-summations
version:     0.0.0.0
synopsis:    Compute number theoretic summations in sublinear time
description: Please see the README on GitHub at <https://github.com/pgujjula/sublinear-summations#readme>
category:    Math
stability:   experimental
github:      "pgujjula/sublinear-summations"
author:      "Preetham Gujjula"
maintainer:  "Preetham Gujjula <libraries@mail.preetham.io>"
copyright:   "Preetham Gujjula"
license:     BSD-3-Clause

language: GHC2021

tested-with:
- GHC == 9.6.5
- GHC == 9.8.2

extra-doc-files:
- README.md
- ChangeLog.md

ghc-options:
- -Wall
- -Wunused-packages

dependencies:
- base ^>= {4.16, 4.17, 4.18, 4.19}

library:
  source-dirs: src
  exposed-modules:
  - Math.NumberTheory.Summation
  - Math.NumberTheory.HyperbolicConvolution
  - Math.NumberTheory.MemoHyper
  - Math.NumberTheory.Mobius
  - SublinearSummation.Util
  dependencies:
  - apply-merge
  - chimera
  - data-ordlist
  - integer-roots
  - placeholder
  - primesieve
  - vector

tests:
  sublinear-summations-tests:
    source-dirs:
    - test
    main: Main.hs
    dependencies:
    - integer-roots
    - sublinear-summations
    - tasty
    - tasty-expected-failure
    - tasty-hunit

benchmarks:
  apply-merge-benchmarks:
    source-dirs:
    - bench
    main: Main.hs
    dependencies:
    - sublinear-summations
    - tasty-bench
    - tasty-expected-failure
    - tasty-hunit
