# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause

resolver: lts-22.44

packages:
- .

build:
  benchmark-opts:
    benchmark-arguments: "--color always"

extra-deps:
- chimera-0.4.1.0
- github: sighingnow/primesieve-haskell
  commit: fbc769804a3be4daf349114cf4ef12920a25cc5b
