# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause

resolver: lts-22.43
compiler: ghc-9.6.7

packages:
- .

build:
  benchmark-opts:
    benchmark-arguments: "--color always"

extra-deps:
- chimera-0.4.1.0
- github: sighingnow/primesieve-haskell
  commit: f80d9cc7bae8c125dbf43a419b52d21c21d3ddbb
  subdirs:
  - primesieve
